# Generated by Django 3.1.7 on 2021-07-25 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening', models.IntegerField(default=0, verbose_name='Opening Balance')),
                ('timestamp', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('total_amt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Sale Time')),
                ('amount', models.IntegerField(default=0)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Desctiption')),
                ('payment_type', models.CharField(choices=[('online', 'online'), ('cash', 'cash')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
