# Generated by Django 3.1.7 on 2021-07-25 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystatement',
            name='statements',
            field=models.ManyToManyField(to='cafe.Sale'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.IntegerField(default=datetime.date.today),
        ),
    ]
