# Generated by Django 3.1.7 on 2021-07-25 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_auto_20210725_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Sale Time'),
        ),
    ]
