# Generated by Django 3.1.7 on 2021-07-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_auto_20210725_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailystatement',
            name='total_amt',
        ),
        migrations.AlterField(
            model_name='dailystatement',
            name='statements',
            field=models.ManyToManyField(blank=True, null=True, to='cafe.Sale'),
        ),
    ]
