# Generated by Django 3.1.7 on 2021-07-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_auto_20210727_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystatement',
            name='timestamp',
            field=models.DateField(unique=True, verbose_name='Date'),
        ),
    ]
